from datetime import datetime


def report_header(module_name: str) -> list[str]:
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    return [
        "=" * 60,
        "Python Network Automation Toolkit v2.0",
        f"Module: {module_name}",
        "=" * 60,
        "",
        f"Scan Time: {timestamp}",
        "",
    ]


def report_footer() -> list[str]:
    return [
        "",
        "=" * 60,
        "End of Report",
        "Generated by Python Network Automation Toolkit",
        "=" * 60,
    ]