import csv
import socket
from datetime import datetime
from pathlib import Path

from report_utils import report_footer, report_header

from colorama import Fore, init

init(autoreset=True)

BASE_DIR = Path(__file__).resolve().parent.parent
OUTPUT_DIR = BASE_DIR / "output"

PORT_RESULTS_FILE = OUTPUT_DIR / "port_scan_results.csv"
PORT_SUMMARY_FILE = OUTPUT_DIR / "port_scan_summary.txt"

COMMON_PORTS = {
    20: "FTP Data",
    21: "FTP Control",
    22: "SSH",
    23: "Telnet",
    25: "SMTP",
    53: "DNS",
    80: "HTTP",
    110: "POP3",
    143: "IMAP",
    443: "HTTPS",
    3389: "RDP",
}


def scan_port(host: str, port: int, timeout: float = 1.0) -> str:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.settimeout(timeout)
        result = sock.connect_ex((host, port))
        return "OPEN" if result == 0 else "CLOSED"


def write_csv(results: list[dict[str, str]]) -> None:
    OUTPUT_DIR.mkdir(exist_ok=True)

    with PORT_RESULTS_FILE.open("w", newline="") as file:
        fieldnames = ["host", "port", "service", "status"]
        writer = csv.DictWriter(file, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(results)


def write_summary(host: str, results: list[dict[str, str]]) -> None:
    open_ports = [item for item in results if item["status"] == "OPEN"]
    closed_ports = [item for item in results if item["status"] == "CLOSED"]

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    lines = [
        "=" * 60,
        "Python Network Automation Toolkit v2.0",
        "Module: TCP Port Scanner",
        "=" * 60,
        "",
        f"Scan Time: {timestamp}",
        f"Target Host: {host}",
        "",
        "Summary:",
        f"- Total Ports Scanned: {len(results)}",
        f"- Open Ports: {len(open_ports)}",
        f"- Closed Ports: {len(closed_ports)}",
        "",
        "Port Results:",
    ]

    for item in results:
        lines.append(
            f"- {item['port']} | {item['service']} | {item['status']}"
        )

    lines.extend(
        [
            "",
            "End of Report",
            "Generated by Python Network Automation Toolkit",
        ]
    )

    lines.extend(report_footer())
    
    PORT_SUMMARY_FILE.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    print(f"{Fore.CYAN}Python Network Automation Toolkit")
    print(f"{Fore.CYAN}TCP Port Scanner")
    print("-" * 50)

    host = input("Enter target IP or hostname: ").strip()

    if not host:
        print(f"{Fore.RED}No host entered.")
        return

    results = []

    print()
    print(f"Scanning {host}...")
    print()

    for port, service in COMMON_PORTS.items():
        status = scan_port(host, port)

        results.append(
            {
                "host": host,
                "port": str(port),
                "service": service,
                "status": status,
            }
        )

        colour = Fore.GREEN if status == "OPEN" else Fore.RED
        print(f"{colour}{port:<6} {service:<12} {status}")

    write_csv(results)
    write_summary(host, results)

    print()
    print(f"{Fore.GREEN}Port scan complete.")
    print(f"{Fore.YELLOW}CSV saved to: {PORT_RESULTS_FILE}")
    print(f"{Fore.YELLOW}Summary saved to: {PORT_SUMMARY_FILE}")


if __name__ == "__main__":
    main()